development:
  secret_token: "my_secret_token"
  secret_key_base: <%= ENV['secret_development_key'] %>

test:
  secret_token: "my_secret_token"
  secret_key_base: <%= ENV['secret_test_key'] %>

production:
  secret_token: "my_secret_token"
  secret_key_base: <%= ENV['secret_key'] %>